services:
  schedule_message:
    build: .
    container_name: schedule_message
    ports:
      - "8080:8080"
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
    depends_on:
      - kafka

  sender_email:
    build: ../sender_email
    container_name: sender_email
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
    depends_on:
      - kafka

  sender_email2:
    build: ../sender_email2
    container_name: sender_email2
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
    depends_on:
      - kafka

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CLUSTER_ID: "4L6_S0DxT96uS7neSAs_6A"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  default:
    driver: bridge